import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const Nohemi = localFont({
  src: [
    {
      path: "../../fonts/Nohemi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
     {
      path: "../../fonts/Nohemi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../fonts/Nohemi-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../fonts/Nohemi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-nohemi", // optional: allows using Tailwind with font-[var]
  display: "block",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Nohemi.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
